galaxy_info:
  author: oasis_roles
  description: Download and install the oc and kubectl binaries to a specified directory
  company: Red Hat, Inc.
  license: GPLv3
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8

  galaxy_tags:
    - oasis

dependencies: []
